* Week 4 (Netflix documentary and Assignment 2)
** Q: What the APA style of writing is, what the Chicago manual style, and what's the difference?
   - 1-2 Pages
   - Email to MichaelCoard@msn.com
   - Due Next Monday
   - Double Space paper, 1-2 pages

** "Separate is inherently unequal"
   - Implement Brown 1 with "All the deliberate speed"
   - Brown 4, When Topeka School District finally met the standards that the Distrcit Court mandated.
     - It wasn't until our lifetime (1998), that the 1954 case was addressed. 
       
** Documentary notes
   - The U.S. has the highest rate of incarceration on the planet.
   - Michelle Alexander, author of the Seminal, new Jim Crow.
   - The film-maker brought the burning cross to realization.
   - 1970 : The U.S. prison population was at 357,292.
     * ten years later, it jumps up to 514,000. (1980)
     * five years later, it jumps up to 760,100. (1985)
   - From rhetoric to reality, from Nixon to Reagan, that's the true story on the War of Drugs.
     * Nixon talked about it, Reagan acted upon it.
   - The Congressional Black Caucus jumped right in bed with Nixon/Reagan. They would see Drugs and Crime and say that's the problem, ignoring Education and other social factors
   - If you're caught with powder cocaine than crack cocaine, one ounce of crack cocaine is equivalent in punishment as to having 100 ounce of powder cocaine.

