* Week 4 (Netflix documentary and Assignment 2)
** Q: What the APA style of writing is, what the Chicago manual style, and what's the difference?
   - 1-2 Pages
   - Email to MichaelCoard@msn.com
   - Due Next Monday
   - Double Space paper, 1-2 pages

** "Separate is inherently unequal"
   - Implement Brown 1 with "All the deliberate speed"
   - Brown 4, When Topeka School District finally met the standards that the Distrcit Court mandated.
     - It wasn't until our lifetime (1998), that the 1954 case was addressed. 
       
** Documentary notes
   - The U.S. has the highest rate of incarceration on the planet.
   - Michelle Alexander, author of the Seminal, new Jim Crow.
   - The film-maker brought the burning cross to realization.
   - 1970 : The U.S. prison population was at 357,292.
     * ten years later, it jumps up to 514,000. (1980)
     * five years later, it jumps up to 760,100. (1985)
     * five years later, it jumps up to 1.2 million (1990)
     * ten years later, it jumps up to 2.01 million (2000)

   - From rhetoric to reality, from Nixon to Reagan, that's the true story on the War of Drugs.
     * Nixon talked about it, Reagan acted upon it.
   - The Congressional Black Caucus jumped right in bed with Nixon/Reagan. They would see Drugs and Crime and say that's the problem, ignoring Education and other social factors
   - If you're caught with powder cocaine than crack cocaine, one ounce of crack cocaine is equivalent in punishment as to having 100 ounce of powder cocaine.
   - ALEC = American Legislative Exchange Council
<<<<<<< HEAD

* What if any is the most effective way of combatting racism
** 3 pages - Typed Written - Double Space (1 page each)
** Submit it in the *APA* format

** Due in Class 
=======
*** More /inmates/, longer /sentences/, more /profit/ !!
   - Bail is a classist concept because a rich white guy, or a rich black guy, on the other hand a poor white/black guy
   - can commit the same crime and the bail is set at $10,000,000 but the rich guy can bail himself out and the other couldn't
   - The whole notion of bail is corrupt because the law says you are "innocent until /proven/ guilty"
   - The system has caused prisons to create monsters amongst the inmates.
   
   - The most *important* lawyer in America, Brian Stevenson, who is the head of the equal justice initiative.
     - Famous
     - He's commited to the documentary and the social injustice of the prison system
   - Collateral Consequences:
     - When you get convicted of certain crimes, you can't live in public housing anymore
     - tends to start robbing people of their wealth because they are unable to provide any type of financial support.
   - Once you've been branded a felon, some of the Jim Crow rights have revived
   - The *WHITE* man, ONE in *SEVENTEEN* in terms of lifetime imprisonment
   - The *BLACK* man, ONE in *THREE* in terms of lifetime imprisonment
     - Black men (6% of the U.S. population) but over *40%* of the jail population
   - /One Slave free, Two Convict leasing, Three Jim Crow/
   - "The only thing necessary for evil to triumph is for good men to do nothing"
   
>>>>>>> 9d992401763df99f3b9875f17a834f080afcf09b
* Week 9
** Racism is an invisible system of discrimination and injustice that was established an is upheld by our social institutions
** $120,000,000,000 government backed home loans
   - White people Only (from 1934-1962)
** Red lining
   - Home loans provided in certain parts of town
   - Realtors would literally put a *red* line on the map
     + created "ghettos"
   - Money was given only in the white part of the town
     + No money was given to the black part of the town
   - Maintained Segregation
   - Deterred investments
   - Economically advantaged whites
   - *EDUCATIONAL ADVANTAGES*
     + /Property Taxes/ fund school - Wealth
   - *EMPLOYEE/CAREER ADVANTAGES*
     + employers are 50% more likely to reply to "white" names. 
   - Black men jailed 6x higher than white men
   - Sentenced for crack is /100x/ harsher than for cocaine
   - 400 years of slavery + 150 years of discrimination

